# Generated by Django 5.2.1 on 2025-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
